import type { ClassType, InputType } from './theme/index.js';
import DropdownContainer from './lib/dropdown/DropdownContainer.vue';
import DropdownContent from './lib/dropdown/DropdownContent.vue';
import Collapse from './lib/collapse/Collapse.vue';
import Sidebar from './lib/sidebar/Sidebar.vue';
import Modal from './lib/modal/Modal.vue';
declare const generateClass: (type: ClassType, value: InputType) => string;
export default generateClass;
export { DropdownContainer, DropdownContent, Collapse, Sidebar, Modal };
export * from './lib/directives/index.js';
export * from './theme/theme.types.js';
export * from './lib/collapse/index.types.js';
