import type { ClassType, InputType } from './theme/index.js';
import DropdownContainer from './lib/dropdown/DropdownContainer.vue';
import DropdownContent from './lib/dropdown/DropdownContent.vue';
import Collapse from './lib/collapse/Collapse.vue';
import Sidebar from './lib/sidebar/Sidebar.vue';
import Modal from './lib/modal/Modal.vue';
import HamburgerMenu from './lib/nav/HamburgerMenu.vue';
declare const generateClass: (type: ClassType, value: InputType) => string;
export default generateClass;
export { DropdownContainer, DropdownContent, Collapse, HamburgerMenu, Sidebar, Modal, };
export * from './lib/directives';
export * from './theme/theme.types';
export * from './lib/collapse/index.types';
